---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cfwheels
  namespace: legacy-modernization
  labels:
    app: cfwheels
spec:
  podSelector:
    matchLabels:
      app: cfwheels
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: cfwheels
      ports:
        - protocol: TCP
          port: 8888
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 3306
