---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-11-config
  namespace: legacy-modernization
  labels:
    app: apollo-11
data:
  APP_ENV: "production"
  APP_NAME: "apollo-11"
  LOG_LEVEL: "info"
  TZ: "UTC"
  NGINX_PORT: "8080"
