---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: legacy-modernization
  labels:
    app: odoo
data:
  APP_ENV: "production"
  APP_NAME: "odoo"
  LOG_LEVEL: "info"
  TZ: "UTC"
  PORT: "8069"
