---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nuxeo
  namespace: legacy-modernization
  labels:
    app: nuxeo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nuxeo
